Mr robot
atom-robotics-lab/wiki pull request #50
Opened 2023-03-13 21:38 UTC by NOEMOJI041

MR ROBOT WIKI
ADDED :-
1) OVERVIEW
2) CODE EXPLANATION
3) MISCELLANEOUS

2023-03-14 19:21 UTC, Kartik9250 commented on markdown/projects/mr-robot/major-code/arduino.rst
> +This code snippet is used to set up the various peripherals and settings needed for the robot to operate, including the ROS node, PWM signals for the motors, encoder signals for the wheels, and inter
Peripherals is not the right word to be used to address the components/parts here

2023-03-14 19:22 UTC, Kartik9250 commented on markdown/projects/mr-robot/major-code/arduino.rst
> +This code defines two callback functions, LpwmCb and RpwmCb, which take a std_msgs::Int32 object as input. The functions control the speed of four motors by writing PWM signals using the ledcWrite fu
Four motors were not used. Write two instead.

2023-03-14 19:22 UTC, Kartik9250 commented on markdown/projects/mr-robot/major-code/arduino.rst
> +This code defines two callback functions, LpwmCb and RpwmCb, which take a std_msgs::Int32 object as input. The functions control the speed of four motors by writing PWM signals using the ledcWrite fu
Add Inline code for highlighting the different code components: LpwmCb, std_msgs

2023-03-14 19:29 UTC, Kartik9250 commented on markdown/projects/mr-robot/major-code/arduino.rst
Define how arduino is communicating the Ros master node

2023-03-14 19:36 UTC, Kartik9250 commented on markdown/projects/mr-robot/major-code/arduino.rst
> +The function publish_encoder_data() is used to publish the encoder values and any associated errors to their respective ROS topics.
inline coments

2023-03-14 19:46 UTC, Kartik9250 requested changes
Use the following tag in order to make it resourceful & easier to read:

- Inline code tags
- Notes, Warnings, Seealso
- Link and cross reference our documentation pages.
- Use the Additional images that were added.
- Proof read the documentation and verify the provided information.
- Add references for the various websites for detailed information.

2023-03-14 20:31 UTC, namikxgithub approved these changes

2023-03-15 05:30 UTC, jasmeet0915 commented
Some changes are required @NOEMOJI041 :
cc: @Kartik9250 @namikxgithub 
 - Mention MR Robot fullform in Project intro(overview) page and it should be written as MR Robot and not Mr. Robot since it is an Acronym.
- Add image captions 
 - Add official Links for packages and hardware components in Working section
 - Add tf tree for the robot in working section
 - Include ros computation graph of nodes in launching section to show topics and nodes that are launched. This can be done using [rqt_graph](http://wiki.ros.org/rqt_graph) node.
 - Doesn't need such big description for Master-Slave. We already cover this in ROS Intro. This section should be named different and it should contain a block diagram showing where the different nodes of the setup run physically. This block diagram is a different from ROS computation graph and not necessarily needs to include topics. But should show where different nodes run (pi, laptop/pc etc.)

2023-03-15 22:28 UTC, NOEMOJI041 commented
Fixed:-
1)Mr. Robot ------> MR Robot
2)Information Check
3)Deleted Extra from Master-Slave and changed its name
Added:-
1)inline code tags
2)Image Captions
3)Official Links in working.rst
4)Note is added in esp-diff-tf.rst and Warning is added to bash.rst
Note:-
tf tree and rqt_graph will be added according to the latest test.

2023-03-16 18:44 UTC, NOEMOJI041 commented
Added TF TREE and Node Graph

2023-03-16 19:44 UTC, Kartik9250 commented on markdown/projects/mr-robot/mr-index.rst
> +Mr robot is autonomous navigation robot made by A.T.O.M Robotics capable of doing multiple day to day operations such as mapping, navigation for transportation, sanitaion etc. Various other operation
Mr robot is an* autonomous

2023-03-16 19:52 UTC, NOEMOJI041 commented on markdown/projects/mr-robot/mr-index.rst
> +Mr robot is autonomous navigation robot made by A.T.O.M Robotics capable of doing multiple day to day operations such as mapping, navigation for transportation, sanitaion etc. Various other operation
done

2023-03-16 19:55 UTC, Kartik9250 approved these changes
Minor changes required, would be updated in next ver

2023-03-16 19:56 UTC, merged